spring.application.name=java-cicd-app
server.port=8080
server.servlet.context-path=/

logging.level.root=INFO
logging.level.com.cicdpractice=DEBUG

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
