name: workflow-1
on:
  push: 
    branches:
      - main 


env: 
  registry: docker.io
  APP_NAME: java-cicd-app
  APP_VERSION: 1.1.0


jobs:
  Code_Checkout :
    runs-on: self-hosted
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Code Fetched Message
        run: echo "the Code is fetched to the runner"

  Build:

    needs: Code_Checkout
    runs-on: self-hosted
    strategy:
      matrix:
        java-version: [8,17,21]
    steps:
      - name: Building The Application with Maven
        uses: actions/setup-java@v4
        with:
         distribution: temurin
         java-version: ${{matrix.java-version:}}

      - name: Checking Maven version
        run: mvn --version

      - name: Cleaning the Old Artifacts
        run: mvn clean package -DskipTests

      - name: storing the new Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: target/  

  Code_Analysis:
    needs: Build
    runs-on: self-hosted
    steps:
      - name: Downlaoding the Artifacts
        uses: actions/download-artifact@v4

      - name: Code Code_Analysis
        run: echo "checking the  code quality and Leakage"

      - name: user info
        run: echo "whoami" 
      - name: Build Docker Image
        run: |
          DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ github.run_number }}
          sudo docker build -t "$DOCKER_IMAGE" .

      - name: Print Docker Image
        run: echo $DOCKER_IMAGE
      - name: Sudo docker images 
        run: sudo docker images                          
  
  Docker_Image:
    needs: Code_Analysis
    runs-on: self-hosted
    steps:
      - name: Print Docker Image
        run: echo $DOCKER_IMAGE
  

  Push_To_DockerHUB:
    needs: Docker_Image
    runs-on: self-hosted 
    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@v4
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Pushing  image to Dockerhub
        run: |
          docker push ${{secrets.DOCKER_USERNAME}}/${{env.APP_NAME}}:${{github.run_number}}


  POST:
    needs: Push_To_DockerHUB
    runs-on: ubuntu-latest
    if: always()
    steps: 
      - name: code checkout
        uses: actions/checkout@v4

      - name: Execution Message
        run: echo "The WorkFlow Execution is completed successfully"         
        